harga_barang = int(input("Masukkan harga barang = "))
uang_pembeli = int(input("Masukkan uang pembeli =  "))

if harga_barang < 0 or uang_pembeli < 0:
    print("Input invalid")
elif harga_barang > uang_pembeli:
    print("uang tidak cukup")
else:
    pecahan_uang = [100000, 50000, 20000, 10000, 5000, 2000, 1000]
    kembalian = uang_pembeli - harga_barang
    for uang in pecahan_uang :
        if kembalian >= uang:
            jumlah = kembalian // uang
            kembalian -= jumlah * uang
            print(jumlah, f"uang sejumlah Rp.{uang}")
        else:
            print(f"0 uang sejumlah Rp.{uang}")
            

            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            





